spring:
  application:
  name: movie.library
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/movie-library?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        ddl-auto: create
        dialect: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
  session:
    store-type: jdbc
server:
  port: 8081
logging.level:
  org:
    springframework:
      web: DEBUG
      security: DEBUG
      security.oauth2: DEBUG

    hibernate: INFO
  com.mcueen.movie.library: DEBUG
springdoc:
  swagger-ui.path: /swagger-ui.html
  api-docs.path: /api-docs