spring:
  application:
  name: movie.library
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/movie-library?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        ddl-auto: create
        dialect: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
  session:
    store-type: jdbc
  data:
    elasticsearch:
      client:
        reactive:
          endpoints: localhost:9200
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: my-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
server:
  port: 8081
logging.level:
  org:
    springframework:
      web: DEBUG
      security: DEBUG
      security.oauth2: DEBUG

    hibernate: INFO
  com.mcueen.movie.library: DEBUG
springdoc:
  swagger-ui.path: /swagger-ui.html
  api-docs.path: /api-docs